Added einops package to requirements.txt
Got error while deploying new image of sbert 
 einops==0.8.0

  File "/opt/app-root/lib64/python3.12/site-packages/transformers/dynamic_module_utils.py", line 181, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`